#!/bin/bash


#######################################################
####################### Aliases #######################
#######################################################

# Add a vim alias
alias vi=nvim
alias vim=nvim

# Eclair
alias gecl="AWS_PROFILE=global ECLRC=$HOME/.eclrc.global ecl"

notify () {
    osascript -e "display notification \"$*\" sound name \"Glass\" with title \"Shell Notification\""
    say "$*"
}

# SCM Breeze
alias gds="gd --staged"

# Terraform
alias tf=terraform

# Mac Power Usage
powerstat() {
    b=$(system_profiler SPPowerDataType)
    power=$(echo "$b" | grep 'Wattage (W):' | cut -d ':' -f 2 | xargs)
    echo "Total Power: $power W"
}

source $HOME/.env
