#!/bin/bash


#######################################################
####################### Aliases #######################
#######################################################

# Add a vim alias
alias vi=nvim
alias vim=nvim

# Eclair
alias gecl="AWS_PROFILE=global ECLRC=$HOME/.eclrc.global ecl"

notify () {
    osascript -e "display notification \"$*\" sound name \"Glass\" with title \"Shell Notification\""
    say "$*"
}

# SCM Breeze
#alias gds="gd --staged"

# Terraform
alias tf=terraform

# Mac Power Usage
powerstat() {
    powerdatatype=$(system_profiler SPPowerDataType)
    power=$(echo "$powerdatatype" | grep 'Wattage (W):' | cut -d ':' -f 2 | xargs)

    smartbat=$(ioreg -rw0 -a -c AppleSmartBattery)
    adapterpower=$(echo "$smartbat" | plutil -extract '0.BatteryData.AdapterPower' raw - | xargs -I %  lldb --batch -o "print/f %" | grep -o '$0 = [0-9.]*' | cut -c 6-)
    systempower=$(echo "$smartbat" | plutil -extract '0.BatteryData.SystemPower' raw - | xargs -I %  lldb --batch -o "print/f %" | grep -o '$0 = [0-9.]*' | cut -c 6-)

    echo "Adapter Power: $adapterpower W"
    echo "System Power:  $systempower W"
    echo "Total Power:   $power W"
}

if exists fdfind; then
    alias fd=fdfind
fi

source $HOME/.my_env
