#!/bin/bash


#######################################################
####################### Aliases #######################
#######################################################

# Add a vim alias
alias vi=nvim
alias vim=nvim

# Eclair
alias gecl="AWS_PROFILE=global ECLRC=$HOME/.eclrc.global ecl"

notify () {
    osascript -e "display notification \"$*\" sound name \"Glass\" with title \"Shell Notification\""
    say "$*"
}

# SCM Breeze
alias gds="gd --staged"

# Terraform
alias tf=terraform

source $HOME/.env
